# authentication providers
auth:
  google: 
    clientID: ""
    clientSecret: ""
    scope: 
      - "profile"
      - "email"
    callbackURL: "http://localhost:3005/auth/google/callback"

elasticsearch:
  host: localhost:9200
  index: curlist
  type: curlist

redis: 
  host: localhost
  port: 6379
  auth_pass: ~

# go into ./locales/ to make translations
locales: ['en']

functions_path: './../../config/functions'
listeners_path: ~

# itemsjs or elasticsearch (not supported yet)
search_engine: 'itemsjs'

# early prototype
#acl:
  #allowed_emails_editing: ['joe.doe@domain.com']
  #allowed_export_types: ['json', 'yaml', 'csv']
  #export_login_required: true
  #filters_count_before_login: 3

per_page_list: [10, 20, 30, 50]

item_display_field: 'id'
user_display_field: 'id'

# for example look into example.yaml
searchable_facets: []

item_schema: ~

filters_page:
  facets_list: []

item_page:
  fields_list: []
  similar_list: []

add_page: 
  fields_list: []

edit_page: 
  fields_list: []

default_sort: id_desc

# customize search behaviour
search:
  sortings: 
    id_asc: 
      field: id
      title: ID asc
      order: asc
    id_desc: 
      field: id
      title: ID desc
      order: desc

general:
  # it's being used as a key for checking duplicates in import
  main_field: ~

export:
  fields: ~ 
  #fields: ['name', 'tags'] 

import:
  # get all fields
  fields: ~
  merge_fields: ~

enrichment:
  fields: ['wtj']

changelog:
  fields: ~

integrations:
  clearbit:
    api_key: ~
  hunter: 
    api_key: ~
  # github.com/digestoo/website-to-json-dockerized
  wtj: 
    url: http://localhost:5000
    path: /wtj
    fields: ~
    #fields: ['meta_title', 'meta_description', 'meta_keywords', 'facebook', 'linkedin']

  # github.com/digestoo/tech-detector
  tech-detector: 
    url: http://localhost:5001
  google-nlp: ~
  fullcontact: ~
