# authentication providers
auth:
  google: 
    clientID: ""
    clientSecret: ""
    scope: 
      - "profile"
      - "email"
    callbackURL: "http://localhost:3005/auth/google/callback"

# go into ./locales/ to make translations
locales: ['en']

functions_path: './../../config/functions'
listeners_path: ~

# itemsjs or elasticsearch (not supported yet)
search_engine: 'itemsjs'

# early prototype
#acl:
  #allowed_emails_editing: ['joe.doe@domain.com']
  #allowed_export_types: ['json', 'yaml', 'csv']
  #export_login_required: true
  #filters_count_before_login: 3

per_page_list: [10, 20, 30, 50]

item_display_field: 'id'
user_display_field: 'id'

# for example look into example.yaml
searchable_facets: []

item_schema: ~

filters_page:
  facets_list: []

item_page:
  fields_list: []
  similar_list: []

add_page: 
  fields_list: []

edit_page: 
  fields_list: []

default_sort: id_desc

# customize search behaviour
search:
  sortings: 
    id_asc: 
      field: id
      title: ID asc
      order: asc
    id_desc: 
      field: id
      title: ID desc
      order: desc
