# authentication providers
auth:
  google: 
    clientID: ""
    clientSecret: ""
    scope: 
      - "profile"
      - "email"
    callbackURL: "http://localhost:3005/auth/google/callback"

# go into ./locales/ to make translations
locales: ['en']

# early prototype
#acl:
  #allowed_emails_editing: ['joe.doe@domain.com']
  #allowed_export_types: ['json', 'yaml', 'csv']
  #export_login_required: true
  #filters_count_before_login: 3

item_display_field: 'id'

# for example look into example.yaml
searchable_facets: []

item_schema: ~

filters_page:
  facets_list: []

item_page:
  fields_list: []
  similar_list: []

add_page: 
  fields_list: []

edit_page: 
  fields_list: []

search: ~
