db:
  dialect: sqlite
  storage: './sqlite/database_test.sqlite'
  database: database_test
  logging: false

functions_path: ~

general:
  main_field: domain

elasticsearch:
  host: localhost:9200
  index: curlist_test
  type: curlist_test

item_schema:
  domain: 
    type: string
  tags: 
    type: array
  genres: 
    type: array
